import AppKit

/// Everything on a pasteboard, so keybro can borrow it and put it back.
public struct PasteboardSnapshot: @unchecked Sendable {
    let items: [[NSPasteboard.PasteboardType: Data]]

    @MainActor
    public static func take(_ pasteboard: NSPasteboard = .general) -> PasteboardSnapshot {
        let items = (pasteboard.pasteboardItems ?? []).map { item in
            Dictionary(uniqueKeysWithValues: item.types.compactMap { type in item.data(forType: type).map { (type, $0) } })
        }
        return PasteboardSnapshot(items: items)
    }

    @MainActor
    public func restore(to pasteboard: NSPasteboard = .general) {
        pasteboard.clearContents()
        let restored = items.map { entries in
            let item = NSPasteboardItem()
            for (type, data) in entries { item.setData(data, forType: type) }
            return item
        }
        if !restored.isEmpty { pasteboard.writeObjects(restored) }
    }
}

@MainActor
public enum Pasteboard {
    /// nspasteboard.org markers so clipboard managers ignore keybro's temporary text.
    static let transientTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    public static func writeTransient(_ text: String, to pasteboard: NSPasteboard = .general) {
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        for type in transientTypes { item.setData(Data(), forType: type) }
        pasteboard.writeObjects([item])
    }

    /// Waits for another app to put text on the pasteboard after a ⌘C.
    public static func waitForString(after changeCount: Int, timeout: Duration = .milliseconds(300), pasteboard: NSPasteboard = .general) async -> String? {
        let deadline = ContinuousClock.now + timeout
        while ContinuousClock.now < deadline {
            if pasteboard.changeCount != changeCount {
                return pasteboard.string(forType: .string)
            }
            try? await Task.sleep(for: .milliseconds(15))
        }
        return nil
    }
}
